import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useQuery } from "@tanstack/react-query";
import { FileSignature, Plus } from "lucide-react";
import { contractsApi } from "@/lib/api";
import { formatDate, STATUS_COLORS, cn } from "@/lib/utils";
export default function ContractsPage() {
    const { data, isLoading } = useQuery({
        queryKey: ["contracts"],
        queryFn: () => contractsApi.list()
    });
    const contracts = data?.data?.results ?? [];
    return (_jsxs("div", { className: "p-4 sm:p-8", children: [_jsxs("div", { className: "flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-xl sm:text-2xl font-bold text-gray-900", children: "Contracts" }), _jsxs("p", { className: "text-gray-500 text-sm mt-0.5", children: [contracts.length, " total"] })] }), _jsxs("button", { className: "flex items-center justify-center gap-2 bg-indigo-600 text-white px-4 py-2.5 rounded-lg text-sm font-medium hover:bg-indigo-700 transition-colors w-full sm:w-auto shadow-sm", children: [_jsx(Plus, { className: "w-4 h-4" }), " New Contract"] })] }), _jsx("div", { className: "bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden", children: _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full min-w-[650px] table-auto", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-gray-100 bg-gray-50/50", children: [_jsx("th", { className: "text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide", children: "Title" }), _jsx("th", { className: "text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide", children: "Type" }), _jsx("th", { className: "text-center px-6 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide", children: "Status" }), _jsx("th", { className: "text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide", children: "End Date" }), _jsx("th", { className: "text-left px-6 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide", children: "Created" })] }) }), _jsxs("tbody", { className: "divide-y divide-gray-50", children: [isLoading && (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "px-6 py-10 text-center text-gray-400", children: "Loading..." }) })), !isLoading && contracts.length === 0 && (_jsx("tr", { children: _jsxs("td", { colSpan: 5, className: "px-6 py-12 text-center", children: [_jsx(FileSignature, { className: "w-10 h-10 text-gray-200 mx-auto mb-2" }), _jsx("p", { className: "text-gray-400 text-sm", children: "No contracts yet." })] }) })), contracts.map((c) => (_jsxs("tr", { className: "hover:bg-gray-50/80 transition-colors", children: [_jsx("td", { className: "px-6 py-4 text-sm font-medium text-gray-900 max-w-[200px] truncate", children: c.title }), _jsx("td", { className: "px-6 py-4 text-sm text-gray-500 capitalize", children: c.contract_type }), _jsx("td", { className: "px-6 py-4 text-center", children: _jsx("span", { className: cn("text-xs font-medium px-2.5 py-1 rounded-full capitalize inline-block text-center min-w-[80px]", STATUS_COLORS[c.status]), children: c.status }) }), _jsx("td", { className: "px-6 py-4 text-sm text-gray-500", children: c.end_date ? formatDate(c.end_date) : "—" }), _jsx("td", { className: "px-6 py-4 text-sm text-gray-500", children: formatDate(c.created_at) })] }, c.id)))] })] }) }) })] }));
}
