# Generated by Django 6.0.5 on 2026-05-27 21:21

import django.db.models.deletion
import notifications.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('security', 'Security alert'), ('password_changed', 'Password changed'), ('two_fa_enabled', '2FA enabled'), ('two_fa_disabled', '2FA disabled'), ('new_login', 'New login detected'), ('invoice_sent', 'Invoice sent'), ('invoice_viewed', 'Invoice viewed by client'), ('invoice_paid', 'Invoice paid'), ('invoice_overdue', 'Invoice overdue'), ('payment_reminder', 'Payment reminder'), ('payment_received', 'Payment received'), ('contract_signed', 'Contract signed'), ('contract_expiring', 'Contract expiring soon'), ('contract_expired', 'Contract expired'), ('ai_review_done', 'AI contract review complete'), ('subscription_upgraded', 'Subscription upgraded'), ('subscription_cancelled', 'Subscription cancelled'), ('payment_failed', 'Payment failed'), ('trial_ending', 'Trial ending soon'), ('system', 'System announcement'), ('compliance_alert', 'Compliance alert'), ('welcome', 'Welcome')], db_index=True, max_length=40)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=10)),
                ('title', models.CharField(max_length=160, verbose_name='title')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='data')),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('channels_requested', models.SmallIntegerField(default=notifications.models.Channel['IN_APP'], help_text='OR of Channel flags requested at creation time.', verbose_name='channels requested')),
                ('channels_sent', models.SmallIntegerField(default=0, help_text='OR of Channel flags actually dispatched.', verbose_name='channels sent')),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='read at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('email_message_id', models.CharField(blank=True, help_text='Returned by SendGrid on successful dispatch.', max_length=255, verbose_name='SendGrid message-id')),
                ('push_ticket_id', models.CharField(blank=True, max_length=255, verbose_name='Expo push ticket id')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx'), models.Index(fields=['user', 'category'], name='notificatio_user_id_4652f6_idx'), models.Index(fields=['category', 'created_at'], name='notificatio_categor_e0e064_idx'), models.Index(fields=['priority', 'created_at'], name='notificatio_priorit_f7c359_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('security', 'Security alert'), ('password_changed', 'Password changed'), ('two_fa_enabled', '2FA enabled'), ('two_fa_disabled', '2FA disabled'), ('new_login', 'New login detected'), ('invoice_sent', 'Invoice sent'), ('invoice_viewed', 'Invoice viewed by client'), ('invoice_paid', 'Invoice paid'), ('invoice_overdue', 'Invoice overdue'), ('payment_reminder', 'Payment reminder'), ('payment_received', 'Payment received'), ('contract_signed', 'Contract signed'), ('contract_expiring', 'Contract expiring soon'), ('contract_expired', 'Contract expired'), ('ai_review_done', 'AI contract review complete'), ('subscription_upgraded', 'Subscription upgraded'), ('subscription_cancelled', 'Subscription cancelled'), ('payment_failed', 'Payment failed'), ('trial_ending', 'Trial ending soon'), ('system', 'System announcement'), ('compliance_alert', 'Compliance alert'), ('welcome', 'Welcome')], db_index=True, max_length=40)),
                ('channels', models.SmallIntegerField(default=notifications.models.Channel['IN_APP'] | notifications.models.Channel['EMAIL'] | notifications.models.Channel['PUSH'], verbose_name='enabled channels')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
                'indexes': [models.Index(fields=['user', 'category'], name='notificatio_user_id_e0a7cc_idx')],
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField(help_text='Expo push token, FCM registration ID, or APNS device token.', unique=True)),
                ('platform', models.CharField(choices=[('expo', 'Expo Push'), ('fcm', 'Firebase (Android)'), ('apns', 'Apple (iOS)'), ('web', 'Web Push')], db_index=True, default='expo', max_length=10)),
                ('device_name', models.CharField(blank=True, help_text="Human-readable label, e.g. 'Alice's iPhone 15'.", max_length=120, verbose_name='device name')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'push token',
                'verbose_name_plural': 'push tokens',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_47d48f_idx'), models.Index(fields=['platform', 'is_active'], name='notificatio_platfor_be8a0e_idx')],
            },
        ),
    ]
