# Generated by Django 5.2.14 on 2026-05-29 22:35

import django.db.models.deletion
import django.utils.timezone
import documents.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('invoice', 'Invoice'), ('quotation', 'Quotation'), ('contract', 'Contract')], db_index=True, max_length=20, verbose_name='document type')),
                ('doc_id', models.UUIDField(db_index=True, verbose_name='document UUID')),
                ('doc_number', models.CharField(blank=True, max_length=50, verbose_name='document number')),
                ('company_id', models.UUIDField(db_index=True, verbose_name='company UUID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('paid', 'Marked Paid'), ('partial', 'Partial Payment Recorded'), ('voided', 'Voided'), ('signed', 'Signed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('converted', 'Converted to Invoice'), ('deleted', 'Soft Deleted'), ('pdf_gen', 'PDF Generated'), ('docx_gen', 'DOCX Generated'), ('email_sent', 'Email Sent'), ('reminder', 'Reminder Sent'), ('ai_review', 'AI Review Completed')], db_index=True, max_length=30, verbose_name='action')),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='actor IP')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'document activity',
                'verbose_name_plural': 'document activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=documents.models._attachment_upload_to, verbose_name='file')),
                ('original_name', models.CharField(max_length=255, verbose_name='original filename')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME type')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='file size (bytes)')),
                ('attachment_type', models.CharField(choices=[('supporting', 'Supporting Document'), ('receipt', 'Receipt / Proof of Payment'), ('signature', 'Signature Image'), ('other', 'Other')], default='supporting', max_length=20, verbose_name='type')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'document attachment',
                'verbose_name_plural': 'document attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('invoice', 'Invoice'), ('quotation', 'Quotation'), ('contract', 'Contract')], max_length=20, verbose_name='document type')),
                ('doc_id', models.UUIDField(db_index=True, verbose_name='document UUID')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='version number')),
                ('snapshot', models.JSONField(default=dict, verbose_name='document snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'document version',
                'verbose_name_plural': 'document versions',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('stripe', 'Stripe'), ('mpesa', 'M-Pesa'), ('cheque', 'Cheque'), ('crypto', 'Cryptocurrency'), ('other', 'Other')], default='bank_transfer', max_length=20, verbose_name='payment method')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='payment date')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='transaction reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='reversed / refunded')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'payment record',
                'verbose_name_plural': 'payment records',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly (Every 2 Weeks)'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual (Every 6 Months)'), ('annual', 'Annual')], default='monthly', max_length=20, verbose_name='frequency')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date (optional)')),
                ('max_occurrences', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='max occurrences')),
                ('occurrences_sent', models.PositiveSmallIntegerField(default=0, verbose_name='occurrences sent')),
                ('next_invoice_date', models.DateField(verbose_name='next invoice date')),
                ('auto_send', models.BooleanField(default=True, verbose_name='auto-send to client')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'recurring invoice',
                'verbose_name_plural': 'recurring invoices',
                'ordering': ['next_invoice_date'],
            },
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='cnt_company_status_idx',
            old_name='documents_c_company_75a2c5_idx',
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='cnt_company_end_date_idx',
            old_name='documents_c_company_9cb91a_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='inv_company_status_idx',
            old_name='documents_i_company_138b9b_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='inv_company_due_date_idx',
            old_name='documents_i_company_289bf0_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='inv_client_status_idx',
            old_name='documents_i_client__ac04c3_idx',
        ),
        migrations.RenameIndex(
            model_name='quotation',
            new_name='qt_company_status_idx',
            old_name='documents_q_company_611bd0_idx',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='contract',
            name='ai_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI reviewed at'),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_salutation',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Mx', 'Mx'), ('', '(none)')], default='', max_length=10, verbose_name='salutation'),
        ),
        migrations.AddField(
            model_name='contract',
            name='hellosign_signature_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/%Y/%m/', verbose_name='signature image'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_salutation',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Mx', 'Mx'), ('', '(none)')], default='', max_length=10, verbose_name='salutation'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='viewed at'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='unit_label',
            field=models.CharField(blank=True, help_text="Display label, e.g. 'm', 'kg', 'hrs'. Shown in PDF column.", max_length=20, verbose_name='unit label'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='unit_of_measure',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Dimensionless multiplier per unit, e.g. metres per roll.', max_digits=10, verbose_name='unit of measure multiplier'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_salutation',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Mx', 'Mx'), ('', '(none)')], default='', max_length=10, verbose_name='salutation'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='decline_reason',
            field=models.TextField(blank=True, verbose_name='decline reason'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='declined at'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='amount paid'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='body',
            field=models.TextField(blank=True, verbose_name='contract body / clauses'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Linked DocFlow user account. Leave blank for external clients.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss_as_client', to=settings.AUTH_USER_MODEL, verbose_name='client (internal user)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client_vat_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='client VAT / TIN'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='currency ISO-4217'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='docusign_envelope_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models._docx_upload_to, verbose_name='DOCX'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-assigned on first save via Company.get_next_*() if blank.', max_length=50, verbose_name='document number'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models._pdf_upload_to, verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='tax'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='amount paid'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Linked DocFlow user account. Leave blank for external clients.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss_as_client', to=settings.AUTH_USER_MODEL, verbose_name='client (internal user)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_vat_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='client VAT / TIN'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='currency ISO-4217'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models._docx_upload_to, verbose_name='DOCX'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-assigned on first save via Company.get_next_*() if blank.', max_length=50, verbose_name='document number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models._pdf_upload_to, verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='portal_token',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='tax'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='item_type',
            field=models.CharField(choices=[('service', 'Service'), ('product', 'Product'), ('expense', 'Expense'), ('discount', 'Discount / Credit'), ('other', 'Other')], default='service', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='sort_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Override company VAT for this line. Leave 0 to use company default.', max_digits=5, verbose_name='per-line tax rate %'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='unit price'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='amount paid'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Linked DocFlow user account. Leave blank for external clients.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss_as_client', to=settings.AUTH_USER_MODEL, verbose_name='client (internal user)'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='client_vat_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='client VAT / TIN'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='currency ISO-4217'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models._docx_upload_to, verbose_name='DOCX'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-assigned on first save via Company.get_next_*() if blank.', max_length=50, verbose_name='document number'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models._pdf_upload_to, verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='tax'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='total'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['company', 'signed_at'], name='cnt_company_signed_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'issue_date'], name='inv_company_issue_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['portal_token'], name='inv_portal_token_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['company', 'valid_until'], name='qt_company_valid_until_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'number'), name='cnt_unique_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='cnt_end_date_gte_start_date'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'number'), name='inv_unique_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='lineitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('invoice__isnull', False), ('quotation__isnull', True)), models.Q(('invoice__isnull', True), ('quotation__isnull', False)), _connector='OR'), name='lineitem_belongs_to_exactly_one_document'),
        ),
        migrations.AddConstraint(
            model_name='lineitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='lineitem_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='lineitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_of_measure__gt', 0)), name='lineitem_unit_of_measure_positive'),
        ),
        migrations.AddConstraint(
            model_name='lineitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='lineitem_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='lineitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='lineitem_discount_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'number'), name='qt_unique_number_per_company'),
        ),
        migrations.AddField(
            model_name='documentactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.contract'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.invoice'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.quotation'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='documents.invoice'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reversals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringinvoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_invoices', to='companies.company'),
        ),
        migrations.AddField(
            model_name='recurringinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_invoices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringinvoice',
            name='template',
            field=models.ForeignKey(help_text='Draft invoice used as the template for each recurrence.', on_delete=django.db.models.deletion.PROTECT, related_name='recurring_schedules', to='documents.invoice'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['doc_type', 'doc_id'], name='activity_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['company_id', 'action'], name='activity_company_action_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['actor', 'created_at'], name='activity_actor_ts_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contract__isnull', True), ('invoice__isnull', False), ('quotation__isnull', True)), models.Q(('contract__isnull', True), ('invoice__isnull', True), ('quotation__isnull', False)), models.Q(('contract__isnull', False), ('invoice__isnull', True), ('quotation__isnull', True)), _connector='OR'), name='attachment_belongs_to_one_document'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['doc_type', 'doc_id', 'version'], name='docversion_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='recurringinvoice',
            index=models.Index(fields=['company', 'is_active', 'next_invoice_date'], name='rec_inv_schedule_idx'),
        ),
    ]
