# Generated by Django 5.2.14 on 2026-05-30 01:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cohort_name', models.CharField(max_length=100)),
                ('cohort_date', models.DateField(db_index=True)),
                ('cohort_type', models.CharField(choices=[('signup_week', 'Signup Week'), ('signup_month', 'Signup Month'), ('signup_quarter', 'Signup Quarter'), ('acquisition_source', 'Acquisition Source')], max_length=50)),
                ('period_0_users', models.IntegerField(default=0)),
                ('period_1_retained', models.IntegerField(default=0)),
                ('period_2_retained', models.IntegerField(default=0)),
                ('period_3_retained', models.IntegerField(default=0)),
                ('period_4_retained', models.IntegerField(default=0)),
                ('period_5_retained', models.IntegerField(default=0)),
                ('period_6_retained', models.IntegerField(default=0)),
                ('period_12_retained', models.IntegerField(default=0)),
                ('total_revenue_generated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_cohorts',
                'ordering': ['-cohort_date'],
                'indexes': [models.Index(fields=['cohort_date', 'cohort_type'], name='analytics_c_cohort__067b79_idx'), models.Index(fields=['cohort_name'], name='analytics_c_cohort__e667d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='RevenueSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('mrr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('arr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('ltv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cac', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_customers', models.IntegerField(default=0)),
                ('active_customers', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('churned_customers', models.IntegerField(default=0)),
                ('trial_customers', models.IntegerField(default=0)),
                ('mrr_starter', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('mrr_pro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('mrr_enterprise', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('churn_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('retention_rate', models.DecimalField(decimal_places=4, default=Decimal('100.0000'), max_digits=5)),
                ('average_revenue_per_user', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_ai_reviews', models.IntegerField(default=0)),
                ('total_documents_generated', models.IntegerField(default=0)),
                ('ai_credits_used', models.IntegerField(default=0)),
                ('data_completeness_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Revenue Snapshots',
                'db_table': 'analytics_revenue_snapshots',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='analytics_r_date_6ed15d_idx'), models.Index(fields=['active_customers', 'mrr'], name='analytics_r_active__3daf04_idx'), models.Index(fields=['churn_rate'], name='analytics_r_churn_r_9fd2c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(choices=[('signup', 'User Signup'), ('subscription_started', 'Subscription Started'), ('subscription_canceled', 'Subscription Canceled'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_upgraded', 'Subscription Upgraded'), ('subscription_downgraded', 'Subscription Downgraded'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('refund_issued', 'Refund Issued'), ('invoice_paid', 'Invoice Paid'), ('ai_review_completed', 'AI Review Completed'), ('document_generated', 'Document Generated'), ('pdf_exported', 'PDF Exported'), ('trial_started', 'Trial Started'), ('trial_ended', 'Trial Ended'), ('churned', 'Customer Churned'), ('reactivated', 'Customer Reactivated'), ('login', 'User Login'), ('feature_used', 'Feature Used'), ('support_ticket', 'Support Ticket')], db_index=True, max_length=50)),
                ('event_name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(default=dict, help_text='Flexible event data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('response_time_ms', models.IntegerField(null=True)),
                ('status_code', models.IntegerField(null=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_test', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Event Logs',
                'db_table': 'analytics_event_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_e_user_id_18a2e4_idx'), models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_8de35a_idx'), models.Index(fields=['company_id', 'event_type'], name='analytics_e_company_f7fb8b_idx'), models.Index(fields=['created_at', 'event_type'], name='analytics_e_created_8865cb_idx'), models.Index(fields=['session_id'], name='analytics_e_session_56b4a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='MRRSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_tier', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise'), ('free_trial', 'Free Trial')], max_length=20)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('previous_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('change_reason', models.CharField(blank=True, max_length=200)),
                ('change_type', models.CharField(choices=[('new', 'New Customer'), ('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('renewal', 'Renewal'), ('cancellation', 'Cancellation')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrr_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_mrr_snapshots',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['user', 'period_start'], name='analytics_m_user_id_257510_idx'), models.Index(fields=['period_start', 'subscription_tier'], name='analytics_m_period__0c948c_idx'), models.Index(fields=['is_active', 'canceled_at'], name='analytics_m_is_acti_3c209b_idx')],
                'unique_together': {('user', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='RevenueAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('mrr_milestone', 'MRR Milestone Reached'), ('churn_spike', 'Churn Rate Spike'), ('payment_failure', 'Payment Failure Spike'), ('upgrade_boost', 'Upgrade Activity Spike'), ('trial_conversion', 'Trial Conversion Milestone')], max_length=50)),
                ('alert_level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('success', 'Success')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('previous_value', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_channel', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'created_at'], name='analytics_a_alert_t_abf070_idx'), models.Index(fields=['alert_level', 'is_resolved'], name='analytics_a_alert_l_a3dcde_idx'), models.Index(fields=['-created_at'], name='analytics_a_created_487842_idx')],
            },
        ),
    ]
