[pytest]
DJANGO_SETTINGS_MODULE = docflow.settings.local
python_files = tests.py test_*.py *_test.py
python_classes = Test*
python_functions = test_*
addopts = --reuse-db -x -v

[coverage:run]
source = apps
omit =
    */migrations/*
    */tests/*
    */admin.py

[coverage:report]
show_missing = true
skip_covered = true
fail_under = 70
