# Generated by Django 6.0.5 on 2026-05-27 19:11

import companies.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='company name')),
                ('slug', models.SlugField(help_text='URL-safe identifier, auto-generated from name.', max_length=220, unique=True, verbose_name='slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=companies.models._logo_upload_path, verbose_name='company logo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='business email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='address line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('country', models.CharField(default='KE', help_text='ISO 3166-1 alpha-2 country code.', max_length=2, verbose_name='country')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='registration number')),
                ('size', models.CharField(choices=[('solo', 'Solo / Freelancer'), ('small', '2–10 employees'), ('medium', '11–50 employees'), ('large', '50+ employees')], default='solo', max_length=20, verbose_name='company size')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='industry')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code.', max_length=3, verbose_name='default currency')),
                ('timezone_name', models.CharField(default='UTC', max_length=60, verbose_name='timezone')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='language')),
                ('date_format', models.CharField(default='%d %b %Y', help_text='Python strftime format string.', max_length=20, verbose_name='date format')),
                ('invoice_prefix', models.CharField(default='INV', max_length=10, verbose_name='invoice prefix')),
                ('quotation_prefix', models.CharField(default='QT', max_length=10, verbose_name='quotation prefix')),
                ('contract_prefix', models.CharField(default='CNT', max_length=10, verbose_name='contract prefix')),
                ('next_invoice_number', models.PositiveIntegerField(default=1)),
                ('next_quotation_number', models.PositiveIntegerField(default=1)),
                ('next_contract_number', models.PositiveIntegerField(default=1)),
                ('default_payment_terms', models.PositiveSmallIntegerField(default=30, verbose_name='default payment terms (days)')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='bank name')),
                ('bank_account_name', models.CharField(blank=True, max_length=100, verbose_name='account name')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='account number')),
                ('bank_branch_code', models.CharField(blank=True, max_length=30, verbose_name='branch / sort code')),
                ('swift_code', models.CharField(blank=True, max_length=20, verbose_name='SWIFT / BIC')),
                ('iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN')),
                ('mpesa_paybill', models.CharField(blank=True, max_length=20, verbose_name='M-Pesa Paybill')),
                ('mpesa_till', models.CharField(blank=True, max_length=20, verbose_name='M-Pesa Till')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_companies', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_color', models.CharField(default='#1A56DB', max_length=7, verbose_name='primary colour')),
                ('secondary_color', models.CharField(default='#6B7280', max_length=7, verbose_name='secondary colour')),
                ('accent_color', models.CharField(default='#10B981', max_length=7, verbose_name='accent colour')),
                ('text_color', models.CharField(default='#111827', max_length=7, verbose_name='text colour')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='background colour')),
                ('font_family', models.CharField(default='Inter', help_text='Google Fonts family name loaded in PDF templates.', max_length=60, verbose_name='font family')),
                ('font_size_body', models.PositiveSmallIntegerField(default=10, verbose_name='body font size (pt)')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to=companies.models._stamp_upload_path, verbose_name='company stamp / seal')),
                ('signature', models.ImageField(blank=True, null=True, upload_to=companies.models._signature_upload_path, verbose_name='authorised signature')),
                ('invoice_header_text', models.TextField(blank=True, verbose_name='invoice header text')),
                ('invoice_footer_text', models.TextField(blank=True, default='Thank you for your business.', verbose_name='invoice footer text')),
                ('quotation_footer_text', models.TextField(blank=True, verbose_name='quotation footer text')),
                ('contract_footer_text', models.TextField(blank=True, verbose_name='contract footer text')),
                ('invoice_terms', models.TextField(blank=True, verbose_name='invoice terms')),
                ('quotation_terms', models.TextField(blank=True, verbose_name='quotation terms')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='companies.company')),
            ],
            options={
                'verbose_name': 'company branding',
                'verbose_name_plural': 'company brandings',
            },
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff'), ('accountant', 'Accountant'), ('client', 'Client')], default=companies.models.MemberRole['STAFF'], max_length=20, verbose_name='workspace role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='joined at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.company')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'company membership',
                'verbose_name_plural': 'company memberships',
            },
        ),
        migrations.CreateModel(
            name='VATConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vat_number', models.CharField(blank=True, max_length=50, verbose_name='VAT / TIN number')),
                ('vat_registered', models.BooleanField(default=False, verbose_name='VAT registered')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, help_text='e.g. 16 for 16 % Kenyan VAT.', max_digits=5, verbose_name='VAT rate (%)')),
                ('vat_label', models.CharField(default='VAT', max_length=20, verbose_name='VAT label')),
                ('wht_applicable', models.BooleanField(default=False, verbose_name='withholding tax applicable')),
                ('wht_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='WHT rate (%)')),
                ('wht_label', models.CharField(default='WHT', max_length=20, verbose_name='WHT label')),
                ('extra_tax_label', models.CharField(blank=True, max_length=20, verbose_name='extra tax label')),
                ('extra_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='extra tax rate (%)')),
                ('prices_include_tax', models.BooleanField(default=False, help_text='If True, line item prices are treated as tax-inclusive.', verbose_name='prices include tax')),
                ('show_tax_breakdown', models.BooleanField(default=True, verbose_name='show tax breakdown on documents')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vat_config', to='companies.company')),
            ],
            options={
                'verbose_name': 'VAT configuration',
                'verbose_name_plural': 'VAT configurations',
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['owner', 'is_active'], name='companies_c_owner_i_443b40_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['slug'], name='companies_c_slug_45751b_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['company', 'is_active'], name='companies_c_company_5e6bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['user', 'is_active'], name='companies_c_user_id_01d566_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companymembership',
            unique_together={('company', 'user')},
        ),
    ]
