# Generated by Django 5.2.14 on 2026-05-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
    ]
