import factory
from factory.django import DjangoModelFactory
from django.contrib.auth import get_user_model
from django.utils import timezone
import uuid

from ai.models import (
    Company, TenantQuota, CompanyMembership, AiModelTier,
    AiReview, PromptTemplate, AiGeneration, RiskScore
)

User = get_user_model()
class UserFactory(DjangoModelFactory):
    class Meta:
        model = User
    
    email = factory.Faker("email")
    # Custom user models typically track first/last name, but if they throw errors next,
    # you can comment them out as well.
    first_name = factory.Faker("first_name")
    last_name = factory.Faker("last_name")

class CompanyFactory(DjangoModelFactory):
    class Meta:
        model = Company

    name = factory.Faker("company")
    domain = factory.Faker("domain_name")


class TenantQuotaFactory(DjangoModelFactory):
    class Meta:
        model = TenantQuota

    company = factory.SubFactory(CompanyFactory)
    max_users = 10
    max_documents_storage_gb = 50.00
    monthly_token_limit = 5000000
    current_monthly_tokens_used = 0
    reset_date = factory.LazyFunction(timezone.localdate)


class CompanyMembershipFactory(DjangoModelFactory):
    class Meta:
        model = CompanyMembership

    user = factory.SubFactory(UserFactory)
    company = factory.SubFactory(CompanyFactory)
    role = CompanyMembership.RoleChoices.MEMBER
    permissions = factory.LazyFunction(lambda: {
        "contracts": {"create": True, "read": True, "update": True, "delete": False},
        "ai_tools": {"execute_review": True, "execute_generation": True},
        "compliance": {"view_alerts": True, "resolve_alerts": False},
        "billing": {"view_quotas": False}
    })


class AiModelTierFactory(DjangoModelFactory):
    class Meta:
        model = AiModelTier

    name = factory.Sequence(lambda n: f"Tier-{n}")
    primary_model = "gpt-4o"
    secondary_fallback = "claude-3-5-sonnet"
    tertiary_fallback = "gpt-4-turbo"
    is_active = True


class AiReviewFactory(DjangoModelFactory):
    class Meta:
        model = AiReview

    company = factory.SubFactory(CompanyFactory)
    created_by = factory.SubFactory(UserFactory)
    document_name = factory.Faker("file_name", extension="pdf")
    status = AiReview.Status.PENDING
    model_used = "gpt-4o"
    tokens_used = 0


class PromptTemplateFactory(DjangoModelFactory):
    class Meta:
        model = PromptTemplate

    company = factory.SubFactory(CompanyFactory)
    name = factory.Faker("word")
    template_type = PromptTemplate.TemplateType.NDA
    system_prompt = "You are an expert legal counsel AI."
    user_prompt = "Review the following NDA text: {text}"
    variables = factory.LazyFunction(lambda: ["text"])
    version = 1
    active = True


class AiGenerationFactory(DjangoModelFactory):
    class Meta:
        model = AiGeneration

    company = factory.SubFactory(CompanyFactory)
    created_by = factory.SubFactory(UserFactory)
    template = factory.SubFactory(PromptTemplateFactory)
    input_fields = factory.LazyFunction(lambda: {"text": "Sample NDA content"})
    generated_content = "This is a legally binding template outcome generated by AI."
    model_used = "gpt-4o"
    tokens_used = 1250


class RiskScoreFactory(DjangoModelFactory):
    class Meta:
        model = RiskScore

    score = 15.50
    risk_breakdown = factory.LazyFunction(lambda: {"indemnity": 10, "liability": 5.5})
    mitigation_strategy = "Add a mutual liability cap clause."
