import pdfplumber
import json
from typing import Dict, Any, List
from django.utils import timezone
from langchain_text_splitters import RecursiveCharacterTextSplitter

from .provider import get_ai_provider
from .prompts.prompt_blueprints import CONTRACT_REVIEW_SYSTEM_PROMPT
from .models import AiReview, RiskScore

class ContractReviewOrchestrator:
    """
    Manages the text extraction, semantic splitting, and risk analysis
    pipeline for uploaded contract payloads.
    """
    def __init__(self, review_instance: AiReview):
        self.review = review_instance
        self.splitter = RecursiveCharacterTextSplitter(
            chunk_size=4000,
            chunk_overlap=400,
            length_function=len
        )

    def extract_text_from_file(self) -> str:
        if not self.review.document_file:
            return self.review.extracted_text
        
        full_text_buffer = []
        with pdfplumber.open(self.review.document_file.path) as pdf:
            for page in pdf.pages:
                text_content = page.extract_text()
                if text_content:
                    full_text_buffer.append(text_content)
        
        extracted_raw_text = "\n".join(full_text_buffer)
        self.review.extracted_text = extracted_raw_text
        self.review.save()
        return extracted_raw_text

    def process_analysis(self) -> Dict[str, Any]:
        self.review.status = AiReview.Status.PROCESSING
        self.review.save()

        try:
            raw_text = self.extract_text_from_file()
            if not raw_text.strip():
                raise ValueError("Target file contains no renderable structural text layout.")

            # Segment heavy legal files safely to respect LLM window limitations
            text_slices = self.splitter.split_text(raw_text)
            aggregated_findings: List[Dict[str, Any]] = []
            cumulative_tokens = 0
            
            ai_engine = get_ai_provider(model_name=self.review.model_used)
            
            # Audit segments iteratively
            for index, segment in enumerate(text_slices):
                user_context_prompt = f"Analyze Segment [{index + 1}/{len(text_slices)}]:\n\n{segment}"
                outcome = ai_engine.generate_response(
                    system_prompt=CONTRACT_REVIEW_SYSTEM_PROMPT,
                    user_prompt=user_context_prompt
                )
                
                cumulative_tokens += outcome["tokens_used"]
                try:
                    parsed_json = json.loads(outcome["content"])
                    if isinstance(parsed_json, list):
                        aggregated_findings.extend(parsed_json)
                    else:
                        aggregated_findings.append(parsed_json)
                except json.JSONDecodeError:
                    aggregated_findings.append({
                        "issue_category": "Parsing Error",
                        "severity": "Low",
                        "clause_context": "Segment block interpretation fallback tracking failure.",
                        "raw_output": outcome["content"]
                    })

            # Calculate a normalized corporate legal exposure score matrix
            risk_score_value = self._calculate_composite_risk(aggregated_findings)

            # Persist tracking parameters to database registries
            self.review.review_results = aggregated_findings
            self.review.tokens_used = cumulative_tokens
            self.review.status = AiReview.Status.COMPLETED
            self.review.completed_at = timezone.now()
            self.review.save()

            RiskScore.objects.create(
                review=self.review,
                score=risk_score_value,
                risk_breakdown={"total_detected_risks": len(aggregated_findings)},
                mitigation_strategy="Review critical compliance anomalies generated by structural analysis items."
            )

            return {"status": "Success", "detected_anomalies": len(aggregated_findings)}

        except Exception as err:
            self.review.status = AiReview.Status.FAILED
            self.review.error_message = str(err)
            self.review.save()
            raise err

    def _calculate_composite_risk(self, findings: List[Dict[str, Any]]) -> float:
        if not findings:
            return 0.0
        weight_index = {"critical": 25.0, "high": 15.0, "medium": 5.0, "low": 1.0}
        accumulated_score = 0.0
        for entry in findings:
            severity_str = str(entry.get("severity", "low")).lower()
            accumulated_score += weight_index.get(severity_str, 1.0)
        return min(float(accumulated_score), 100.0)
