# Generated by Django 5.2.14 on 2026-05-30 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('quickbooks', 'QuickBooks'), ('xero', 'Xero'), ('slack', 'Slack'), ('google_drive', 'Google Drive'), ('zapier', 'Zapier')], max_length=50)),
                ('credentials', models.JSONField(default=dict, help_text='Encrypted OAuth tokens and configuration')),
                ('status', models.CharField(choices=[('active', 'Active'), ('degraded', 'Degraded'), ('inactive', 'Inactive'), ('error', 'Error'), ('pending', 'Pending Authentication')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default integration for this type')),
                ('auto_sync_enabled', models.BooleanField(default=False)),
                ('sync_frequency', models.CharField(choices=[('manual', 'Manual'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('realtime', 'Real-time')], default='manual', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=50)),
                ('last_error', models.TextField(blank=True)),
                ('total_syncs', models.IntegerField(default=0)),
                ('successful_syncs', models.IntegerField(default=0)),
                ('failed_syncs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='SyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('invoices', 'Invoices'), ('contacts', 'Contacts'), ('payments', 'Payments'), ('all', 'All Data')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='pending', max_length=20)),
                ('items_processed', models.IntegerField(default=0)),
                ('items_succeeded', models.IntegerField(default=0)),
                ('items_failed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
                ('sync_metadata', models.JSONField(default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_history', to='intergrations.integrationconfig')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], max_length=10)),
                ('event_type', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, default=dict, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('integration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='intergrations.integrationconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='integrationconfig',
            index=models.Index(fields=['company', 'integration_type', 'status'], name='intergratio_company_c843aa_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationconfig',
            index=models.Index(fields=['last_sync_at'], name='intergratio_last_sy_70ab10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integrationconfig',
            unique_together={('company', 'integration_type')},
        ),
        migrations.AddIndex(
            model_name='synchistory',
            index=models.Index(fields=['company', 'integration', '-started_at'], name='intergratio_company_fb5d89_idx'),
        ),
        migrations.AddIndex(
            model_name='synchistory',
            index=models.Index(fields=['status', 'started_at'], name='intergratio_status_2dfa6d_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['company', 'direction', '-created_at'], name='intergratio_company_115706_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['event_type', 'created_at'], name='intergratio_event_t_141c32_idx'),
        ),
    ]
