# Generated by Django 6.0.5 on 2026-05-29 20:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=4, help_text='Credit value equivalent consumed.', max_digits=12)),
                ('transaction_type', models.CharField(choices=[('debit', 'Consumption Charge'), ('credit', 'Quota Allocation Top-Up'), ('refund', 'Failed Processing Reversal')], max_length=20)),
                ('action_summary', models.CharField(help_text='E.g., Contract Review Extraction Run', max_length=255)),
                ('reference_entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_entity_id', models.UUIDField(blank=True, null=True)),
                ('meta_telemetry', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'transaction_type'], name='ai_creditus_company_2521e2_idx'), models.Index(fields=['reference_entity_type', 'reference_entity_id'], name='ai_creditus_referen_dc8e8c_idx')],
            },
        ),
    ]
